---

- name: Clone oh-my-zsh git repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ zsh_ohmyzsh }}"

- name: Clone powerlevel9k oh-my-zsh theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ zsh_custom }}/themes/powerlevel9k"

- name: Create symlink for powerlevel9k oh-my-zsh theme
  file:
    src: "{{ zsh_custom }}/themes/powerlevel9k/powerlevel9k.zsh-theme"
    dest: "{{ zsh_custom }}/themes/powerlevel9k.zsh-theme"
    state: link
    force: yes

- name: Clone spaceship-prompt oh-my-zsh theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ zsh_custom }}/themes/spaceship-prompt"

- name: Create symlink for spaceship-prompt oh-my-zsh theme
  file:
    src: "{{ zsh_custom }}/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ zsh_custom }}/themes/spaceship.zsh-theme"
    state: link
    force: yes

- name: Write .zshrc config
  template:
    src: zshrc.j2
    dest: "{{ zsh_config }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_group }}"
    backup: yes

- name: Change shell for user running playbook to zsh
    user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh
